### ISSUE TITLE
Set Up Your Kanban board

### ISSUE THREAD

**Issue by TEMESGEN-G25** [TEMESGEN-G25/space-travels-hub#25]
> - Here is the link to the project: (https://github.com/NatiG25/Space-Travels-Hub).
### We are a group of two students (@sarazaToussaint, @NatiG25).

 > - Student A is @sarazaToussaint .
 > - Student B is @NatiG25  .

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
